package br.com.nimblebaas.payment_gateway.enums.exception;

public enum BusinessRules {
    
    INVALID_INPUT_DATA,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    TOKEN_REQUIRED,
    INVALID_CREDENTIALS,
    INVALID_TOKEN,
    INVALID_PASSWORD,
    CHARGE_DESTINATION_SAME_AS_ORIGINATOR,
    AUTHORIZER_SERVICE_NOT_FOUND,
    AUTHORIZER_SERVICE_ERROR,
    ACCOUNT_NOT_FOUND,
    INVALID_AMOUNT_TO_DEPOSIT,
    INVALID_AMOUNT_TO_WITHDRAWAL,
    INSUFFICIENT_BALANCE,
    AUTHORIZATION_FAILED,
    CHARGE_PAYMENT_SERVICE_NOT_FOUND,
    CHARGE_NOT_FOUND, 
    CHARGE_PAYMENT_ERROR,
    CHARGE_NOT_ALLOWED_TO_PAY
}
